### PR TITLE
231 - Update art details page

### LINKED ISSUE #231: Update art details page
This task is to update the artwork details page. **This task does not involve anything with the Transfer History.** We will leave that for another ticket, for now it will remain under the other elements. Note that the buttons are different depending on if you are the owner or not.

Must remain responsive.

Screen Shot 2024-04-23 at 9 37 56 PM

### PR DESCRIPTION
**Pull request by ghostman2311**
Closes #231

### CODE REVIEW

**Comment by ghostman2311** [comment]
image

**Comment by buckyroberts** [comment]
This task is not supposed to include any changes to the Transfer History: https://github.com/thenewboston-developers/thenewboston-Frontend/issues/231#issue-2260095388

Screen Shot 2024-04-26 at 7 50 39 PM

**Comment by buckyroberts** [comment]
Random text is appearing red now.

Screen Shot 2024-04-26 at 7 53 02 PM

Screen Shot 2024-04-26 at 7 52 57 PM

**Comment by buckyroberts** [comment]
There should be no buy button if the art is not for sale.

Screen Shot 2024-04-26 at 7 53 48 PM

**Comment by ghostman2311** [comment]
Close #231

**Pull request closed without merging**
